### ISSUE TITLE
Не сохраняются настройки свойств инфоблока

### ISSUE THREAD

**Issue by ibadin** [bitrix-expert/tools#15]
При подключении библиотеки кнопка сохранить срабатывает в холостую в настройках свойст инфоблока
![2017-03-06_19-57-25](https://cloud.githubusercontent.com/assets/3139465/23615158/4f1e86e2-02a7-11e7-8448-5b3fa49541a8.png)

**Comment by niksamokhvalov** [comment]
Что значит «срабатывает в холостую»?

**Comment by ibadin** [comment]
Нажимаю на кнопку "Сохранить" и ничего не происходит, даже окно не закрывается

**Comment by alex-didus** [comment]
При изменении свойства инфоблока, а конкретно опции "Показывать в умном фильтре" и "Вид в умном фильтре" не сохраняет изменения
```
Argument 'type' is null or empty (100)
/home/bitrix/vendor/bitrix-expert/tools/src/Iblock/IblockFinder.php:200
#0: Bex\Tools\Iblock\IblockFinder-&gt;prepareFilter(array)
	/home/bitrix/vendor/bitrix-expert/tools/src/Iblock/IblockFinder.php:56
#1: Bex\Tools\Iblock\IblockFinder-&gt;__construct(array)
	/home/bitrix/vendor/bitrix-expert/tools/src/Iblock/IblockFinder.php:442
#2: Bex\Tools\Iblock\IblockFinder::onAfterIBlockUpdate(array)
	
#3: call_user_func_array(array, array)
	/home/bitrix/www/bitrix/modules/main/classes/general/module.php:475
#4: ExecuteModuleEventEx(array, array)
	/home/bitrix/www/bitrix/modules/iblock/classes/general/iblock.php:1090
#5: CAllIBlock-&gt;Update(NULL, array)
	/home/bitrix/www/bitrix/modules/iblock/admin/iblock_edit_property.php:567
#6: require(string)
	/home/bitrix/www/bitrix/admin/iblock_edit_property.php:1
```

**Comment by niksamokhvalov** [comment]
Какая версия Bex\Tools у вас установлена?

**Comment by alex-didus** [comment]
` "bitrix-expert/tools": "^1.5", `

**Comment by ibadin** [comment]
У меня 1.5.1

**Comment by xdpugachevx** [comment]
Баг подтвердился.
Действительно, ошибка появляется при попытке сохранить вид в умном фильтре.

Проблемный участок здесь: `\Bex\Tools\Iblock\IblockFinder::onAfterIBlockUpdate` http://joxi.ru/brRYNRwhJBgn5A

В $fields['ID'] приходит `0`

**Comment by niksamokhvalov** [comment]
Всем спасибо, будем исправлять.

**Comment by niksamokhvalov** [comment]
Исправление проблемы в ветке `1.x`, прошу проверить. Позже будет релиз.
