### ISSUE TITLE
[floating bug] Периодически теряются поля

### ISSUE THREAD

**Issue by akmetainfo** [bitrix-expert/tools#6]
Попробовал поставить инструменты на новый разрабатываемый сайт. Обнаружил странную плавающую ошибку: время от времени на какой-нибудь странице, которую уже давно сделал и всё в ней работает вылетает сообщение вида:

```
[Bex\Tools\ValueNotFoundException] 
Property ID by iblock #5 and property code "POLISH_ID" not found (0)
/www/mysite.tld/www/vendor/bitrix-expert/tools/src/Iblock/IblockFinder.php:304
#0: Bex\Tools\Iblock\IblockFinder->getValueIblockShard(array, array)
    /www/mysite.tld/www/vendor/bitrix-expert/tools/src/Iblock/IblockFinder.php:219
#1: Bex\Tools\Iblock\IblockFinder->getValue(array, array, integer)
    /www/mysite.tld/www/vendor/bitrix-expert/tools/src/Finder.php:167
#2: Bex\Tools\Finder->getFromCache(array, integer)
    /www/mysite.tld/www/vendor/bitrix-expert/tools/src/Iblock/IblockFinder.php:129
#3: Bex\Tools\Iblock\IblockFinder->propId(string)
    /www/mysite.tld/www/polish/add/index.php:12
```

Поле такое, разумеется есть. F5 на странице делать бесполезно (напоминаю: сайт только разрабатывается, все кэши отключены), сообщение не пропадает.
А вот если пройти в админку в автокэширование и сбросить управляемый кэш -- страница тут же начинает отображаться нормально. Второй раз наблюдаю за неделю подобный баг.
Что за глюк? Где-то в коде неконсистентное обновление кэша?

В продакшн такое выводить и потом постоянно сбрасывать кэш? Б-р-р-р...

На всякий пожарный параметры системы: 
centos7 + php5.4.16 (nginx -> httpd)
bitrix 15.5.10 standard (demo licence)
установка через композер, подключено в local/php_interface/init.php первой строкой
Автокеширование компонентов выключено.
Кэш - apcu

**Comment by niksamokhvalov** [comment]
Удалось ли выявить какую-то закономерность? Например, исключение может выскакивать после создания нового ИБ, свойства, и т. п.?

**Comment by akmetainfo** [comment]
Возникает однозначно значительно позже создания нового ИБ или свойства. Поясню.

Разворачивается пустой битрикс (ну, не совсем: скриптами разворачивается, но всё что нужно сбрасываю), затем из гита накатываю последнюю рабочую версию, вхожу в админку, жму "установить модуль" (самописный) и он устанавливает пяток инфоблоков и заливает в каждый до тысячи строк тестовых данных.
Работаешь, работаешь... день, два -- а потом при заходе на одну из страниц вдруг видишь эксепшн.

Кроме инсталлятора модуля никаких инфоблоков и полей не создаётся - это раз.
Процитированное поле находится на инфоблоке 5, это самый используемый инфоблок и одно из самых частых полей - это два.

Поэтому я могу сделать вполне однозначный вывод, что происходит это значительно позже после создания ИБ, иначе бы я это сразу замечал. Структуру инфоблоков я меняю ну от силы раз в неделю, а чаще раз в две.

Я смотрел ваш код, очень грамотно написано (потому и остановился в итоге), смотрел и после того, как баг поймал -- возможно, дело и не в самом коде, а в каких-то особенностях окружения.

**Comment by niksamokhvalov** [comment]
Обнаружил проблему, имя ей — сборщик кеша. Думаю, что вы столкнулись с тем же. Например, когда через админку добавляется новое свойство в ИБ, кеш сбрасывается и пересобирается на событии `onAfterIBlockAdd` или `onAfterIBlockUpdate`. Но в этот момент новое свойство ещё не создано, поэтому кеш будет собран с устаревшими данными.

Первое, что приходит в голову, сделать перехватчики событий создания, обновления и удаления свойств, но в Битриксе нет события `OnBeforeIBlockPropertyDelete`. Поэтому, видимо придётся отказаться от предварительной генерации кеша по ИБ, но можно оставить генерацию тонкого кеша, содержащего список идентификаторов всех ИБ. А в качестве бонуса доработать `runCacheCollector()` таким образом, что бы его можно было вручную вызвать для генерации полного кеша по конкретному ИБ.

**Comment by niksamokhvalov** [comment]
@akmetainfo буду признателен, если закинете пул-реквест с исправлением :-)

**Comment by mmjurov** [comment]
А что если просто удалить вызов runCacheCollector()? Кеш тогда соберется на следующем хите.
Или другой вариант - можно отложить запуск runCacheCollector() до события onEpilog. Понятно, что страница может не дожить до этого состояния, но опять же на следующем хите кеш соберет себя сам.

**Comment by niksamokhvalov** [comment]
Отказываться от предварительной генерации кеша ой как не хочется. Эта фича особо полезна на высоких нагрузках, для избежания конкурирующих запросов на генерацию.

Идея с onEpilog отличная :+1:. Но потребуются доработки:
1. После создания / обновления ИБ удаляем тонкий кеш и кеш инфоблока. Генерируем тонкий кеш. В статическое свойство-массив пишем идентификатор изменённого ИБ.
2. В onEpilog из статического свойства-массива забираем идентификаторы и проверяем по ним существование кеша ИБ. Если у кого-то нет — запускаем разогрев.
3. Нужно добавить обработчики событий `OnAfterIBlockPropertyAdd` и `OnAfterIBlockPropertyUpdate`.
4. В ТП «Битрикса» пишем письмо с просьбой добавить событие `OnAfterIBlockPropertyDelete` :)

_Тонкий кеш_ — кеш, содержащий идентификаторы всех инфоблоков.
_Кеш ИБ_ — кеш конкретного инфоблока и его свойств.

Если до onEpilog не дойдёт, сработает по-старинке, на следующем хите.

Вроде бы это должно покрыть все проблемы, связанные с обновлением инфоблоков и их свойств как в админке, так и через вызов АПИ.

**Comment by mmjurov** [comment]
На следующей неделе попробую выкрасть время на доработку. А ты, тогда, стукни битриксоидам на тему OnAfterIBlockPropertyDelete. У тебя авторитета больше :)

**Comment by niksamokhvalov** [comment]
Битриксоиды взяли в работу, будем ждать.

> Я передал в отдел разработки заявку на доработку такого функционала.
> После закрытия заявки в текущее обращение придет автоматическое уведомление.
> Когда доработка будет реализована, уведомление будет содержать номер версии модуля с исправлением.

**Comment by niksamokhvalov** [comment]
@akmetainfo в ветке `1.x` появилась доработка, предположительно решающая вашу проблему. Если получится, пожалуйста, проверьте на своём проекте этот фикс.
